
AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  port:
    Type: Number
    Description: container port

Resources:
  NginxTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: nginx-example
      Cpu: 1024
      Memory: 3072
      NetworkMode: awsvpc
      RequiresCompatibilities: ['FARGATE']
      ContainerDefinitions:
        - Name: nginx
          Image: nginx:latest
          Essential: true
          PortMappings:
            - ContainerPort: !Ref port
              HostPort: !Ref port
              Protocol: tcp
