
AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  port:
    Type: Number
    Description: コンテナのポート番号

Resources:
  NginxTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: nginx-example
      Memory: 1024
      ContainerDefinitions:
        - Name: nginx
          Image: nginx:latest
          Essential: true
          PortMappings:
            - ContainerPort: !Ref port
              HostPort: !Ref port
              Protocol: tcp